export const ProductInitial = {
  _id: "",
  name: "",
  description: "",
  price: 0,
  productCode: 0,
  quantity: 0,
  tag: "",
  disCount: { isSale: false, salePercent: 0 },
  categoryId: { _id: "", name: "" },
  subCategoryName: "",
  brandName: "",
  images: [],
  createdAt: "",
  updatedAt: "",
  selectedQuantity: 0,
  shopId: { shopName: "", _id: "" },
};
